theme: jekyll-theme-architect
title: Joseph Cefoli
description: Technologist
logo: https://avatars0.githubusercontent.com/u/6618013?s=460&v=4
image: https://avatars0.githubusercontent.com/u/6618013?s=460&v=4
is_user_page: true
social:
  name: Joe Cefoli
  links:
    - https://twitter.com/jcefoli
    - https://www.linkedin.com/in/josephcefoli
    - https://github.com/jcefoli
    - https://keybase.io/jcefoli
twitter:
  username: jcefoli
plugins:
  - jekyll-seo-tag
